"""auth and per-user ownership

Revision ID: 57924f8aade2
Revises: 14438b1216ca
Create Date: 2026-09-25 13:30:21.209642

Introduces users, sessions, and per-user ownership of every domain table.

**No data-migration path (pre-1.0 PoC).** Existing domain rows have no owner to
attach to, and inventing one would silently hand another account's data to the
first user created. So this migration *aborts* if any user-owned domain table
(company_profile, client, invoice, invoice_line, number_sequence) already has
rows: recreate the database instead. ``vat_rate`` is excluded — it is global
seeded reference data and is expected to be populated.

What it does:
- creates ``user`` and ``user_session``;
- adds a NOT NULL ``owner_id`` FK (ON DELETE RESTRICT) to company_profile,
  client, invoice, number_sequence;
- turns company_profile from a global singleton (CHECK id = 1) into a per-user
  singleton (UNIQUE owner_id), with an autoincrement id;
- makes invoice numbers unique per owner (UNIQUE(owner_id, number) WHERE number
  IS NOT NULL) so two users can both hold INV-2026-00001;
- makes number_sequence keyed per owner (composite PK (owner_id, key)).

The immutability triggers (revision 14438b1216ca) are unchanged in structure;
their DDL now also asserts owner_id is unchanged on issued->void, which is
late-bound in plpgsql and so is valid even though the column is added here.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57924f8aade2"
down_revision: str | Sequence[str] | None = "14438b1216ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# User-owned domain tables that must be empty before ownership can be added.
# vat_rate is intentionally excluded (global seeded reference data).
_OWNED_TABLES = ("company_profile", "client", "invoice", "invoice_line", "number_sequence")

_INVOICE_NUMBER_WHERE = sa.text("number IS NOT NULL")


def _abort_if_data_present(bind) -> None:
    for table in _OWNED_TABLES:
        count = bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        if count:
            raise RuntimeError(
                f"Cannot add per-user ownership: {table} already has {count} row(s). "
                "This pre-1.0 migration has no data-migration path — recreate the "
                "database from scratch (drop and re-run migrations) instead."
            )


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _abort_if_data_present(bind)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    op.create_table(
        "user_session",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index("ix_user_session_user_id", "user_session", ["user_id"])

    # company_profile: global singleton -> per-user singleton.
    op.drop_constraint("ck_company_profile_single_row", "company_profile", type_="check")
    op.execute("ALTER TABLE company_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.add_column("company_profile", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_company_profile_owner",
        "company_profile",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint("uq_company_profile_owner", "company_profile", ["owner_id"])

    # client
    op.add_column("client", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_index("ix_client_owner_id", "client", ["owner_id"])
    op.create_foreign_key(
        "fk_client_owner", "client", "user", ["owner_id"], ["id"], ondelete="RESTRICT"
    )

    # invoice: per-owner unique numbering.
    op.add_column("invoice", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_index("ix_invoice_owner_id", "invoice", ["owner_id"])
    op.create_foreign_key(
        "fk_invoice_owner", "invoice", "user", ["owner_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_index("uq_invoice_number", table_name="invoice", postgresql_where=_INVOICE_NUMBER_WHERE)
    op.create_index(
        "uq_invoice_owner_number",
        "invoice",
        ["owner_id", "number"],
        unique=True,
        postgresql_where=_INVOICE_NUMBER_WHERE,
    )

    # number_sequence: composite PK (owner_id, key).
    op.add_column("number_sequence", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.drop_constraint("number_sequence_pkey", "number_sequence", type_="primary")
    op.create_primary_key("number_sequence_pkey", "number_sequence", ["owner_id", "key"])
    op.create_foreign_key(
        "fk_number_sequence_owner",
        "number_sequence",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    """Downgrade schema — restore the pre-ownership, single-tenant schema."""
    # number_sequence
    op.drop_constraint("fk_number_sequence_owner", "number_sequence", type_="foreignkey")
    op.drop_constraint("number_sequence_pkey", "number_sequence", type_="primary")
    op.create_primary_key("number_sequence_pkey", "number_sequence", ["key"])
    op.drop_column("number_sequence", "owner_id")

    # invoice
    op.drop_index(
        "uq_invoice_owner_number", table_name="invoice", postgresql_where=_INVOICE_NUMBER_WHERE
    )
    op.create_index(
        "uq_invoice_number",
        "invoice",
        ["number"],
        unique=True,
        postgresql_where=_INVOICE_NUMBER_WHERE,
    )
    op.drop_constraint("fk_invoice_owner", "invoice", type_="foreignkey")
    op.drop_index("ix_invoice_owner_id", table_name="invoice")
    op.drop_column("invoice", "owner_id")

    # client
    op.drop_constraint("fk_client_owner", "client", type_="foreignkey")
    op.drop_index("ix_client_owner_id", table_name="client")
    op.drop_column("client", "owner_id")

    # company_profile: per-user singleton -> global singleton.
    op.drop_constraint("uq_company_profile_owner", "company_profile", type_="unique")
    op.drop_constraint("fk_company_profile_owner", "company_profile", type_="foreignkey")
    op.drop_column("company_profile", "owner_id")
    op.execute("ALTER TABLE company_profile ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.create_check_constraint("ck_company_profile_single_row", "company_profile", "id = 1")

    op.drop_index("ix_user_session_user_id", table_name="user_session")
    op.drop_table("user_session")
    op.drop_table("user")
